export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const CART_INCREMENT_ITEM = 'CART_INCREMENT_ITEM';
export const CART_DECREMENT_ITEM = 'CART_DECREMENT_ITEM';

export const CLEAR_CART = 'CLEAR_CART';