// create an order
export const ORDER_CREATE_START = 'ORDER_CREATE_START';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET  = 'ORDER_CREATE_RESET ';

// retrive info for an order
export const ORDER_DETAILS_START = 'ORDER_DETAILS_START';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// pay for an order
export const ORDER_PAY_START = 'ORDER_PAY_START';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

// list my orders
export const ORDER_MY_LIST_START = 'ORDER_MY_LIST_START';
export const ORDER_MY_LIST_SUCCESS = 'ORDER_MY_LIST_SUCCESS';
export const ORDER_MY_LIST_FAIL = 'ORDER_MY_LIST_FAIL';
export const ORDER_MY_LIST_RESET = 'ORDER_MY_LIST_RESET';

// Reset Orders
export const ORDER_RESET = 'ORDER_RESET';

// List Orders (Admin)
export const ORDER_LIST_START = 'ORDER_LIST_START'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

// Mark Order as Delivered (Admin)
export const ORDER_DELIVER_START = 'ORDER_DELIVER_START'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'